[WIP] Add compatibility with Arches installed apps changes in 7.5
archesproject/arches-for-science-prj pull request #1268
Opened 2023-08-17 21:53 UTC by jacobtylerwalls

Refs archesproject/arches#9426

Next step is to create an example client project that can consume arches for science as of this PR and verify things work!

2023-08-17 21:53 UTC, jacobtylerwalls commented on afs/package.json
> +        "arches": "archesproject/arches#9304-cbyrd-arches-installed-packages",
TODO: adjust this as soon as the branch is merged in

2023-08-31 20:36 UTC, chiatt requested changes
This looks great, but It looks like we can safely delete this file `afs/webpack/webpack-node-modules-aliases.js`.  Could you remove it?

2023-08-31 21:28 UTC, chiatt approved these changes

2023-08-31 21:29 UTC, chiatt commented
It appears `afs/webpack/webpack-node-modules-aliases.js` was added to the project by the `update_project` [command](https://github.com/archesproject/arches/blob/deadd9d812788e767d45e2806adab9a42c042d38/arches/management/commands/updateproject.py#L28).  Given that, we should probably leave it in AFS until we're sure it's not needed.

2023-08-31 21:29 UTC, merged