Add thumbnail to sampling image step, #843
archesproject/arches-for-science-prj pull request #924
Opened 2022-07-06 20:22 UTC by njkim

Add thumbnails to the image service selector in the image steps
sample taking workflow
analysis area workflow

2022-09-09 20:30 UTC, chiatt requested changes
This works great Namjun. I did notice that the text and radio button are misaligned because of some upper and lower margins. 

![image](https://user-images.githubusercontent.com/1877663/189437789-ebcc5cd1-cada-4c36-82d1-193766a8b491.png)

Could you center them?

2022-09-13 19:30 UTC, njkim commented
Thanks.
Re-centered them also moved styles tags to css.

> This works great Namjun. I did notice that the text and radio button are misaligned because of some upper and lower margins.
> 
> ![image](https://user-images.githubusercontent.com/1877663/189437789-ebcc5cd1-cada-4c36-82d1-193766a8b491.png)
> 
> Could you center them?

2022-09-14 00:51 UTC, chiatt commented
Thanks Namjun - It's mostly the text and radio button that look misaligned to me. I was thinking it should look more like this:

![image](https://user-images.githubusercontent.com/1877663/190034486-bd46e815-3336-44f1-82f7-5089a82e4797.png)

2022-09-14 01:02 UTC, chiatt approved these changes

2022-09-14 01:02 UTC, merged