Group Members & Larger Entities in Group Reports #960
archesproject/arches-for-science-prj pull request #988
Opened 2022-09-22 04:17 UTC by johnatawnclementawn

The Group Members and Larger Entities tabs on the group report are now populated with the people and/or groups that are belong to a group or encapsulate the current group, respectively. A note about this implementation as it stands, only people and groups that are directly related will be shown. That is to say, any person or group with 2 degrees of separation from the current group will not be shown on this report.

2022-09-27 16:39 UTC, aarongundel commented
@johnatawnclementawn can you resolve the merge conflict here?

2022-09-28 04:20 UTC, johnatawnclementawn commented
@aarongundel resolved conflicts. Ready for merge.

2022-09-28 20:54 UTC, aarongundel requested changes
This looks good and works for me, just one issue with a header.

2022-09-28 20:54 UTC, aarongundel commented on afs/templates/views/components/reports/group.htm
> +                    <h2 class="afs-report-section-title"><i data-bind="click: function() {toggleVisibility(visible.largerEntities)}, css: {'fa-angle-double-right': visible.largerEntities(), 'fa-angle
The text here should probably be changed to "Larger Entitites"

2022-09-28 22:58 UTC, aarongundel approved these changes
Looks good!

2022-09-28 22:58 UTC, merged